#!/bin/sh
#
# Small wrapper that takes the secret files from the folder
#
###############################################################################
crypt4gh-wrap /secret/testcineca.sk /secret/ega_key.c4gh.pub $(cat sftpkeypassword) $@
